AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'DynamoDB creation'
Parameters:
  TimeToLiveSeconds:
    Description: "Timeout DDB records should expire in seconds default 14400=4hrs"
    Default: "14400"
    Type: Number
  Notify:
    Description: "Email address to notify, CreateSNSTopic would need to be true"
    Type: String
  CreateSNSTopic:
    Description: "Whether I should create SNS Topic"
    Default: false
    Type: String
    AllowedValues: [true, false]
  WebhookURL:
    Description: "Webhook URL, CreateWebwook would need to be true"
    Type: String
  CreateWebhook:
    Description: "Whether I should enable webhooks"
    Default: false
    Type: String
    AllowedValues: [true, false]
Conditions:
  ShouldCreateSNS:
    !Equals [true, !Ref CreateSNSTopic]
  ShouldCreateWebhook:
    !Equals [true, !Ref CreateWebhook]
  WebhookNull:
    !Equals ["", !Ref WebhookURL]
Resources:
  SHDIssuesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "arn"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "arn"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: TRUE
  SHDSNSTopic:
    Type: AWS::SNS::Topic
    Condition: ShouldCreateSNS
    Properties:
      Subscription:
        - Endpoint: !Ref 'Notify'
          Protocol: "email"
      TopicName: "SHDNotify"
  SNSParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/SHDIssues/SNS/Topic"
      Type: "String"
      Value: !If [ShouldCreateSNS, !Ref SHDSNSTopic, "empty"]
      Description: "SNS Topic Arn"
  SNSEnabledParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/SHDIssues/SNS/Enabled"
      Type: "String"
      Value: !If [ShouldCreateSNS, true, false]
      Description: "Is SNS notification Enabled"
  WebhookParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/SHDIssues/Webhook/URL"
      Type: "String"
      Value: !If [WebhookNull, "empty", !Ref WebhookURL]
      Description: "Webhook URL"
  WebhookEnabledParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/SHDIssues/Webhook/Enabled"
      Type: "String"
      Value: !If [ShouldCreateWebhook, true, false]
      Description: "Is Webhook notification Enabled"        
Outputs:
  TableIssueName:
    Value: !Ref 'SHDIssuesTable'
    Description: Table issues name of the newly created DynamoDB table
